#region

using System.Diagnostics;
using Forge.Framework.Draw;
using Forge.Framework.Resources;
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
using Rectangle = MonoGameUtility.Rectangle;

#endregion

namespace Forge.Framework.UI.Elements{
    public class Panel : DraggableCollection{
        readonly Sprite2D _background;
        readonly int _backgroundInset = 1;
        readonly string _bgMaterial = "Materials/TextBoxBG";
        readonly string _borderMaterial = "Materials/TextBoxBorder";
        readonly int _borderThickness = 2;
        readonly string _cornerMaterial = "Materials/TextBoxCorner";
        readonly int _cornerSize = 2;
        readonly int _padding;


        public Panel(UIElementCollection parent, FrameStrata.Level depth, Rectangle boundingBox, string alias, string template = "UiTemplates/Panel.json")
            : base(parent, depth, boundingBox, alias + "_Panel"){
            #region load template

            var jobj = Resource.LoadJObject(template);

            _borderMaterial = jobj["BorderMaterial"].ToObject<string>();
            _bgMaterial = jobj["BackgroundMaterial"].ToObject<string>();
            _cornerMaterial = jobj["CornerMaterial"].ToObject<string>();
            _backgroundInset = jobj["BackgroundInset"].ToObject<int>();
            _borderThickness = jobj["BorderThickness"].ToObject<int>();
            _cornerSize = jobj["CornerSize"].ToObject<int>();
            _padding = jobj["Padding"].ToObject<int>();

            #endregion

            #region set up sprites/spritedata

            _background = new Sprite2D
                (
                GenerateBgSprite(boundingBox.Width, boundingBox.Height),
                boundingBox.X,
                boundingBox.Y,
                boundingBox.Width,
                boundingBox.Height,
                this.FrameStrata,
                FrameStrata.Level.Background
                );

            AddElement(_background);

            #endregion
        }

        /// <summary>
        /// Add a new panel element. Important to use this rather than the classic AddElement
        /// to take advantage of the padding/proportional positioning.
        /// The element passed to this function may be initialized with any valid position,
        /// however that position will be overriden by the method when it uses the additional
        /// parameters to calculate the final position of the element.
        /// </summary>
        /// <param name="element"></param>
        /// <param name="destCell"> </param>
        public void AddPanelElement(UIElementCollection element, PanelCell destCell){
            //we assume that when element was initialized, panel was passed as the parent.
            //that way we dont need to this.AddElement()
            element.X = destCell.Area.X + this.X;
            element.Y = destCell.Area.Y + this.X;
        }

        public void AddPanelElement(IUIElement element, PanelCell destCell){
            element.X = destCell.Area.X + this.X;
            element.Y = destCell.Area.Y + this.X;
            this.AddElement(element);
        }

        /// <summary>
        /// Generates the background of the inputbox. optimize: cache the sprites generated by this method in a static dict
        /// </summary>
        /// <param name="boxWidth"></param>
        /// <param name="boxHeight"></param>
        /// <returns></returns>
        Texture2D GenerateBgSprite(int boxWidth, int boxHeight){
            //reflect border material
            var borderTexture = Resource.LoadContent<Texture2D>(_borderMaterial);
            RenderTarget2D reflectedBorder = new RenderTarget2D(Resource.Device, borderTexture.Height, borderTexture.Width);
            {
                var sb = new SpriteBatch(Resource.Device);
                Resource.Device.SetRenderTarget(reflectedBorder);
                Resource.Device.Clear(Color.Transparent);
                sb.Begin(SpriteSortMode.Texture, BlendState.AlphaBlend, SamplerState.PointClamp, DepthStencilState.Default, RasterizerState.CullNone);

                sb.Draw
                    (
                        borderTexture,
                        new Vector2(borderTexture.Width/4f, borderTexture.Height/2f),
                        new Rectangle(0, 0, borderTexture.Width, borderTexture.Height),
                        Color.White,
                        MathHelper.PiOver2,
                        new Vector2(borderTexture.Width/4f, borderTexture.Height/2f),
                        1,
                        SpriteEffects.None,
                        0
                    );
                sb.End();
                Resource.Device.SetRenderTarget(null);
            }

            //now construct background sprite
            var bgBatch = new SpriteBatch(Resource.Device);
            var bgTexture = new RenderTarget2D(Resource.Device, boxWidth, boxHeight);
            Resource.Device.SetRenderTarget(bgTexture);
            Resource.Device.Clear(Color.Transparent);
            bgBatch.Begin(SpriteSortMode.Immediate, BlendState.AlphaBlend);

            bgBatch.Draw
                (
                    Resource.LoadContent<Texture2D>(_bgMaterial),
                    new Rectangle
                        (
                        _backgroundInset,
                        _backgroundInset,
                        boxWidth - _backgroundInset*2,
                        boxHeight - _backgroundInset*2
                        ),
                    Color.White
                );

            //top border
            bgBatch.Draw
                (
                    reflectedBorder,
                    new Rectangle
                        (
                        _cornerSize,
                        0,
                        boxWidth - _cornerSize*2,
                        _borderThickness
                        ),
                    Color.White
                );

            //left  border
            bgBatch.Draw
                (
                    Resource.LoadContent<Texture2D>(_borderMaterial),
                    new Rectangle
                        (
                        0,
                        _cornerSize,
                        _borderThickness,
                        boxHeight - _cornerSize*2
                        ),
                    Color.White
                );

            //right border
            bgBatch.Draw
                (
                    Resource.LoadContent<Texture2D>(_borderMaterial),
                    new Rectangle
                        (
                        boxWidth - _borderThickness,
                        _cornerSize,
                        _borderThickness,
                        boxHeight - _cornerSize*2
                        ),
                    null,
                    Color.White,
                    0,
                    Vector2.Zero,
                    SpriteEffects.FlipHorizontally,
                    1
                );

            //bottom border
            bgBatch.Draw
                (
                    reflectedBorder,
                    new Rectangle
                        (
                        _cornerSize,
                        boxHeight - _borderThickness,
                        boxWidth - _cornerSize*2,
                        _borderThickness
                        ),
                    null,
                    Color.White,
                    0,
                    Vector2.Zero,
                    SpriteEffects.FlipVertically,
                    1
                );


            //topleft corner
            bgBatch.Draw
                (
                    Resource.LoadContent<Texture2D>(_cornerMaterial),
                    new Rectangle
                        (
                        0,
                        0,
                        _cornerSize,
                        _cornerSize
                        ),
                    Color.White
                );

            //topright corner
            bgBatch.Draw
                (
                    Resource.LoadContent<Texture2D>(_cornerMaterial),
                    new Rectangle
                        (
                        boxWidth - _cornerSize,
                        0,
                        _cornerSize,
                        _cornerSize
                        ),
                    null,
                    Color.White,
                    0,
                    Vector2.Zero,
                    SpriteEffects.FlipVertically,
                    1
                );

            //bottomleft corner
            bgBatch.Draw
                (
                    Resource.LoadContent<Texture2D>(_cornerMaterial),
                    new Rectangle
                        (
                        0,
                        boxHeight - _cornerSize,
                        _cornerSize,
                        _cornerSize
                        ),
                    null,
                    Color.White,
                    0,
                    Vector2.Zero,
                    SpriteEffects.FlipHorizontally,
                    1
                );

            //bottomright corner
            bgBatch.Draw
                (
                    Resource.LoadContent<Texture2D>(_cornerMaterial),
                    new Rectangle
                        (
                        boxWidth - _cornerSize,
                        boxHeight - _cornerSize,
                        _cornerSize,
                        _cornerSize
                        ),
                    null,
                    Color.White,
                    0,
                    Vector2.Zero,
                    SpriteEffects.FlipHorizontally | SpriteEffects.FlipVertically,
                    1
                );

            bgBatch.End();
            Resource.Device.SetRenderTarget(null);
            return bgTexture;
        }

        protected void SetBackgroundDims(Rectangle dims){
            _background.X = dims.X;
            _background.Y = dims.Y;
            _background.Width = dims.Width;
            _background.Height = dims.Height;
        }

        /// <summary>
        /// Generates a cell that can be used to position panel elements.
        /// </summary>
        /// <returns></returns>
        public PanelCell GeneratePanelCell(){
            var temp = new PanelCell(0, 0, this.Width, this.Height, _padding);
            return temp.CreateChild(0, 0, 1, 1);
        }

        #region Nested type: PanelCell

        public class PanelCell{
            public readonly Rectangle Area;
            readonly int _padding;

            public PanelCell(int x, int y, int width, int height, int padding){
                Area = new Rectangle(x, y, width, height);
                _padding = padding;
            }

            public PanelCell CreateChild(float x, float y, float width, float height){
                float scaledX = x*Area.Width;
                float scaledY = y*Area.Height;

                int xFinal = (int) (Area.X + scaledX);
                int yFinal = (int) (Area.Y + scaledY);

                int widthFinal = (int) (Area.Width*width);
                int heightFinal = (int) (Area.Height*height);

                Debug.Assert(Area.Contains(new Rectangle(xFinal, yFinal, widthFinal, heightFinal)));

                int xPadding;
                int yPadding;

                if (x == 0){
                    xPadding = _padding;
                }
                else{
                    xPadding = _padding/2;
                }
                if (y == 0){
                    yPadding = _padding;
                }
                else{
                    yPadding = _padding/2;
                }

                xFinal += xPadding;
                yFinal += yPadding;

                if (width == 1){
                    widthFinal -= xPadding*2;
                }
                else{
                    widthFinal -= xPadding*2 - _padding/2;
                }

                if (height == 1){
                    heightFinal -= yPadding*2;
                }
                else{
                    heightFinal -= yPadding*2 - _padding/2;
                }
                return new PanelCell(xFinal, yFinal, widthFinal, heightFinal, _padding);
            }
        }

        #endregion
    }
}